create table public.body_circumference_measurements (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  site text not null,
  measured_at timestamptz not null,
  circumference_cm numeric(7,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint body_circumference_measurements_site_check check (
    site in (
      'neck',
      'shoulders',
      'chest',
      'waist',
      'hips',
      'upper_arm_left',
      'upper_arm_right',
      'forearm_left',
      'forearm_right',
      'thigh_left',
      'thigh_right',
      'calf_left',
      'calf_right'
    )
  ),
  constraint body_circumference_measurements_value_check check (
    circumference_cm > 0 and circumference_cm < 1000
  )
);

comment on table public.body_circumference_measurements is
  'Owner-scoped raw standardized tape-measure circumference observations. Missing dates remain missing; values are never interpolated or extrapolated.';
comment on column public.body_circumference_measurements.site is
  'Stable bounded body-site identifier defined by the Heracles circumference protocol.';
comment on column public.body_circumference_measurements.circumference_cm is
  'Raw user-entered circumference observation in centimetres.';

create index body_circumference_measurements_owner_site_measured_at_idx
  on public.body_circumference_measurements (owner_id, site, measured_at desc, id desc);

alter table public.body_circumference_measurements enable row level security;

create policy "Owners can read body circumference measurements"
  on public.body_circumference_measurements
  for select
  to authenticated
  using (auth.uid() = owner_id);

create policy "Owners can insert body circumference measurements"
  on public.body_circumference_measurements
  for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "Owners can update body circumference measurements"
  on public.body_circumference_measurements
  for update
  to authenticated
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "Owners can delete body circumference measurements"
  on public.body_circumference_measurements
  for delete
  to authenticated
  using (auth.uid() = owner_id);

revoke all on table public.body_circumference_measurements from anon;
grant select, insert, update, delete on table public.body_circumference_measurements to authenticated;
grant usage, select on sequence public.body_circumference_measurements_id_seq to authenticated;
