begin;

create temporary table movement_muscle_matrix_import (
  payload jsonb not null
) on commit drop;

insert into movement_muscle_matrix_import (payload)
values (
  convert_from(
    decode($matrix_payload$eyJtdXNjbGVzIjpbIlBlY3RvcmFsaXMgTWFqb3Ig4oCUIENsYXZpY3VsYXIiLCJQZWN0b3JhbGlzIE1ham9yIOKAlCBTdGVybm9jb3N0YWwiLCJQZWN0b3JhbGlzIE1pbm9yIiwiQW50ZXJpb3IgRGVsdG9pZCIsIkxhdGVyYWwgRGVsdG9pZCIsIlBvc3RlcmlvciBEZWx0b2lkIiwiTGF0aXNzaW11cyBEb3JzaSIsIlRlcmVzIE1ham9yIiwiVXBwZXIgVHJhcGV6aXVzIiwiTWlkZGxlIFRyYXBleml1cyIsIkxvd2VyIFRyYXBleml1cyIsIlJob21ib2lkcyIsIlNlcnJhdHVzIEFudGVyaW9yIiwiTHVtYmFyIEVyZWN0b3IgU3BpbmFlIiwiQmljZXBzIEJyYWNoaWkiLCJCcmFjaGlhbGlzIiwiQnJhY2hpb3JhZGlhbGlzIiwiVHJpY2VwcyBCcmFjaGlpIOKAlCBMb25nIEhlYWQiLCJUcmljZXBzIEJyYWNoaWkg4oCUIExhdGVyYWwgSGVhZCIsIlRyaWNlcHMgQnJhY2hpaSDigJQgTWVkaWFsIEhlYWQiLCJXcmlzdCBGbGV4b3JzIiwiV3Jpc3QgRXh0ZW5zb3JzIiwiRmluZ2VyIEZsZXhvcnMgLyBHcmlwIiwiUmVjdHVzIEFiZG9taW5pcyIsIk9ibGlxdWVzIiwiSWxpb3Bzb2FzIiwiR2x1dGV1cyBNYXhpbXVzIiwiR2x1dGV1cyBNZWRpdXMgKyBNaW5pbXVzIiwiQWRkdWN0b3IgTWFnbnVzIiwiT3RoZXIgSGlwIEFkZHVjdG9ycyIsIlJlY3R1cyBGZW1vcmlzIiwiVmFzdHVzIExhdGVyYWxpcyIsIlZhc3R1cyBNZWRpYWxpcyIsIlZhc3R1cyBJbnRlcm1lZGl1cyIsIkJpY2VwcyBGZW1vcmlzIOKAlCBMb25nIEhlYWQiLCJCaWNlcHMgRmVtb3JpcyDigJQgU2hvcnQgSGVhZCIsIlNlbWl0ZW5kaW5vc3VzIiwiU2VtaW1lbWJyYW5vc3VzIiwiR2FzdHJvY25lbWl1cyIsIlNvbGV1cyJdLCJwYXR0ZXJucyI6W3siY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAuOCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgTHVtYmFyIEludGVydmVydGVicmFsIEZsZXhpb24gKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBMdW1iYXIgSW50ZXJ2ZXJ0ZWJyYWwgRmxleGlvbiAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjEiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJGcm9udGFsIFBsYW5lIEFjZXRhYnVsb2ZlbW9yYWwgQWRkdWN0aW9uIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiRnJvbnRhbCBQbGFuZSBBY2V0YWJ1bG9mZW1vcmFsIEFkZHVjdGlvbiAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAiLCIwIiwiMCIsIjAuMyIsIjAuOCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgQWNldGFidWxvZmVtb3JhbCBGbGV4aW9uIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiU2FnaXR0YWwgUGxhbmUgQWNldGFidWxvZmVtb3JhbCBGbGV4aW9uIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAiLCIwLjgiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAuOCIsIjAiLCIwLjgiLCIwLjgiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgQWNldGFidWxvZmVtb3JhbCBFeHRlbnNpb24gKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBBY2V0YWJ1bG9mZW1vcmFsIEV4dGVuc2lvbiAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjEiLCIxIiwiMSIsIjAuNCIsIjAiXSwibmFtZSI6IlNhZ2l0dGFsIFBsYW5lIFRpYmlvZmVtb3JhbCBGbGV4aW9uIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiU2FnaXR0YWwgUGxhbmUgVGliaW9mZW1vcmFsIEZsZXhpb24gKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjEiLCIxIiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgVGliaW9mZW1vcmFsIEV4dGVuc2lvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IlNhZ2l0dGFsIFBsYW5lIFRpYmlvZmVtb3JhbCBFeHRlbnNpb24gKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMSJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgVGFsb2NydXJhbCBQbGFudGFyZmxleGlvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IlNhZ2l0dGFsIFBsYW5lIFRhbG9jcnVyYWwgUGxhbnRhcmZsZXhpb24gKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwLjQiLCIxIiwiMC42IiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlRyYW5zdmVyc2UgUGxhbmUgU2NhcHVsb3Rob3JhY2ljIFJldHJhY3Rpb24gKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJUcmFuc3ZlcnNlIFBsYW5lIFNjYXB1bG90aG9yYWNpYyBSZXRyYWN0aW9uIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMC43IiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiVHJhbnN2ZXJzZSBQbGFuZSBTY2FwdWxvdGhvcmFjaWMgUHJvdHJhY3Rpb24gKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJUcmFuc3ZlcnNlIFBsYW5lIFNjYXB1bG90aG9yYWNpYyBQcm90cmFjdGlvbiAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAuOCIsIjAiLCIwLjkiLCIwIiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiRnJvbnRhbCBQbGFuZSBTY2FwdWxvdGhvcmFjaWMgVXB3YXJkIFJvdGF0aW9uIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiRnJvbnRhbCBQbGFuZSBTY2FwdWxvdGhvcmFjaWMgVXB3YXJkIFJvdGF0aW9uIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMC43IiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiRnJvbnRhbCBQbGFuZSBTY2FwdWxvdGhvcmFjaWMgRG93bndhcmQgUm90YXRpb24gKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJGcm9udGFsIFBsYW5lIFNjYXB1bG90aG9yYWNpYyBEb3dud2FyZCBSb3RhdGlvbiAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAuOCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMCIsIjAuMyIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiRnJvbnRhbCBQbGFuZSBTY2FwdWxvdGhvcmFjaWMgRGVwcmVzc2lvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IkZyb250YWwgUGxhbmUgU2NhcHVsb3Rob3JhY2ljIERlcHJlc3Npb24gKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwLjIiLCIwIiwiMC44IiwiMCIsIjEiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlNhZ2l0dGFsIFBsYW5lIFNjYXB1bG90aG9yYWNpYyBQb3N0ZXJpb3IgVGlsdCAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IlNhZ2l0dGFsIFBsYW5lIFNjYXB1bG90aG9yYWNpYyBQb3N0ZXJpb3IgVGlsdCAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAuMiIsIjAuNSIsIjAuNSIsIjAiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJUcmFuc3ZlcnNlIFBsYW5lIFNjYXB1bG90aG9yYWNpYyBFeHRlcm5hbCBSb3RhdGlvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IlRyYW5zdmVyc2UgUGxhbmUgU2NhcHVsb3Rob3JhY2ljIEV4dGVybmFsIFJvdGF0aW9uIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAuNCIsIjAuOCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAuMyIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IkZyb250YWwgUGxhbmUgR2xlbm9odW1lcmFsIEFkZHVjdGlvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IkZyb250YWwgUGxhbmUgR2xlbm9odW1lcmFsIEFkZHVjdGlvbiAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwLjQiLCIxIiwiMC4zIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiRnJvbnRhbCBQbGFuZSBHbGVub2h1bWVyYWwgQWJkdWN0aW9uIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiRnJvbnRhbCBQbGFuZSBHbGVub2h1bWVyYWwgQWJkdWN0aW9uIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAuOSIsIjAuNCIsIjAiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAuMyIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlNhZ2l0dGFsIFBsYW5lIEdsZW5vaHVtZXJhbCBGbGV4aW9uIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiU2FnaXR0YWwgUGxhbmUgR2xlbm9odW1lcmFsIEZsZXhpb24gKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAuMyIsIjAiLCIwIiwiMCIsIjAuOCIsIjEiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMC41IiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgR2xlbm9odW1lcmFsIEV4dGVuc2lvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IlNhZ2l0dGFsIFBsYW5lIEdsZW5vaHVtZXJhbCBFeHRlbnNpb24gKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMC44IiwiMSIsIjAiLCIwLjYiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlRyYW5zdmVyc2UgUGxhbmUgR2xlbm9odW1lcmFsIEhvcml6b250YWwgQWRkdWN0aW9uIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiVHJhbnN2ZXJzZSBQbGFuZSBHbGVub2h1bWVyYWwgSG9yaXpvbnRhbCBBZGR1Y3Rpb24gKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiVHJhbnN2ZXJzZSBQbGFuZSBHbGVub2h1bWVyYWwgSG9yaXpvbnRhbCBBYmR1Y3Rpb24gKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJUcmFuc3ZlcnNlIFBsYW5lIEdsZW5vaHVtZXJhbCBIb3Jpem9udGFsIEFiZHVjdGlvbiAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwLjciLCIxIiwiMC4zIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2NhcHVsYXIgUGxhbmUgR2xlbm9odW1lcmFsIEVsZXZhdGlvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IlNjYXB1bGFyIFBsYW5lIEdsZW5vaHVtZXJhbCBFbGV2YXRpb24gKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMSIsIjAuNSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJTYWdpdHRhbCBQbGFuZSBIdW1lcm91bG5hciBGbGV4aW9uIChSYWRpb3VsbmFyIFN1cGluYXRlZCkgKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBIdW1lcm91bG5hciBGbGV4aW9uIOKAlCBSYWRpb3VsbmFyIFN1cGluYXRlZCAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAuNyIsIjEiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlNhZ2l0dGFsIFBsYW5lIEh1bWVyb3VsbmFyIEZsZXhpb24gKFJhZGlvdWxuYXIgTmV1dHJhbCkgKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBIdW1lcm91bG5hciBGbGV4aW9uIOKAlCBSYWRpb3VsbmFyIE5ldXRyYWwgKER5bmFtaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwLjQiLCIxIiwiMC45IiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlNhZ2l0dGFsIFBsYW5lIEh1bWVyb3VsbmFyIEZsZXhpb24gKFJhZGlvdWxuYXIgUHJvbmF0ZWQpIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiU2FnaXR0YWwgUGxhbmUgSHVtZXJvdWxuYXIgRmxleGlvbiDigJQgUmFkaW91bG5hciBQcm9uYXRlZCAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAuOCIsIjEiLCIwLjkiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgSHVtZXJvdWxuYXIgRXh0ZW5zaW9uIChHbGVub2h1bWVyYWwgTmV1dHJhbCkgKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBIdW1lcm91bG5hciBFeHRlbnNpb24g4oCUIEdsZW5vaHVtZXJhbCBOZXV0cmFsIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAuOSIsIjAuOSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJTYWdpdHRhbCBQbGFuZSBIdW1lcm91bG5hciBFeHRlbnNpb24gKEdsZW5vaHVtZXJhbCBGbGV4ZWQpIChEeW5hbWljKSIsInNvdXJjZV9uYW1lIjoiU2FnaXR0YWwgUGxhbmUgSHVtZXJvdWxuYXIgRXh0ZW5zaW9uIOKAlCBHbGVub2h1bWVyYWwgRmxleGVkIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMC41IiwiMSIsIjAuOSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJTYWdpdHRhbCBQbGFuZSBIdW1lcm91bG5hciBFeHRlbnNpb24gKEdsZW5vaHVtZXJhbCBFeHRlbmRlZCkgKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBIdW1lcm91bG5hciBFeHRlbnNpb24g4oCUIEdsZW5vaHVtZXJhbCBFeHRlbmRlZCAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjEiLCIwIiwiMC40IiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlNhZ2l0dGFsIFBsYW5lIFJhZGlvY2FycGFsIEZsZXhpb24gKER5bmFtaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBSYWRpb2NhcnBhbCBGbGV4aW9uIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlNhZ2l0dGFsIFBsYW5lIE1ldGFjYXJwb3BoYWxhbmdlYWwgRmxleGlvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IlNhZ2l0dGFsIFBsYW5lIE1ldGFjYXJwb3BoYWxhbmdlYWwgRmxleGlvbiAoRHluYW1pYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJTYWdpdHRhbCBQbGFuZSBJbnRlcnBoYWxhbmdlYWwgRmxleGlvbiAoRHluYW1pYykiLCJzb3VyY2VfbmFtZSI6IlNhZ2l0dGFsIFBsYW5lIEludGVycGhhbGFuZ2VhbCBGbGV4aW9uIChEeW5hbWljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAuOCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgTHVtYmFyIEludGVydmVydGVicmFsIEZsZXhpb24gKElzb21ldHJpYykiLCJzb3VyY2VfbmFtZSI6IlNhZ2l0dGFsIFBsYW5lIEx1bWJhciBJbnRlcnZlcnRlYnJhbCBGbGV4aW9uIChJc29tZXRyaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjEiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgTHVtYmFyIEludGVydmVydGVicmFsIEV4dGVuc2lvbiAoSXNvbWV0cmljKSIsInNvdXJjZV9uYW1lIjoiU2FnaXR0YWwgUGxhbmUgTHVtYmFyIEludGVydmVydGVicmFsIEV4dGVuc2lvbiAoSXNvbWV0cmljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwLjMiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiVHJhbnN2ZXJzZSBQbGFuZSBMdW1iYXIgSW50ZXJ2ZXJ0ZWJyYWwgUm90YXRpb24gKElzb21ldHJpYykiLCJzb3VyY2VfbmFtZSI6IlRyYW5zdmVyc2UgUGxhbmUgTHVtYmFyIEludGVydmVydGVicmFsIFJvdGF0aW9uIChJc29tZXRyaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwLjIiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJGcm9udGFsIFBsYW5lIEFjZXRhYnVsb2ZlbW9yYWwgQWJkdWN0aW9uIChJc29tZXRyaWMpIiwic291cmNlX25hbWUiOiJGcm9udGFsIFBsYW5lIEFjZXRhYnVsb2ZlbW9yYWwgQWJkdWN0aW9uIChJc29tZXRyaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMCIsIjAuOCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMC44IiwiMCIsIjAuOCIsIjAuOCIsIjAiLCIwIl0sIm5hbWUiOiJTYWdpdHRhbCBQbGFuZSBBY2V0YWJ1bG9mZW1vcmFsIEV4dGVuc2lvbiAoSXNvbWV0cmljKSIsInNvdXJjZV9uYW1lIjoiU2FnaXR0YWwgUGxhbmUgQWNldGFidWxvZmVtb3JhbCBFeHRlbnNpb24gKElzb21ldHJpYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAuNCIsIjEiLCIwLjYiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiVHJhbnN2ZXJzZSBQbGFuZSBTY2FwdWxvdGhvcmFjaWMgUmV0cmFjdGlvbiAoSXNvbWV0cmljKSIsInNvdXJjZV9uYW1lIjoiVHJhbnN2ZXJzZSBQbGFuZSBTY2FwdWxvdGhvcmFjaWMgUmV0cmFjdGlvbiAoSXNvbWV0cmljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMC44IiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjEiLCIwIiwiMC4zIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJGcm9udGFsIFBsYW5lIFNjYXB1bG90aG9yYWNpYyBEZXByZXNzaW9uIChJc29tZXRyaWMpIiwic291cmNlX25hbWUiOiJGcm9udGFsIFBsYW5lIFNjYXB1bG90aG9yYWNpYyBEZXByZXNzaW9uIChJc29tZXRyaWMpIn0seyJjb2VmZmljaWVudHMiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJuYW1lIjoiU2FnaXR0YWwgUGxhbmUgUmFkaW9jYXJwYWwgRXh0ZW5zaW9uIChJc29tZXRyaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBSYWRpb2NhcnBhbCBFeHRlbnNpb24gKElzb21ldHJpYykifSx7ImNvZWZmaWNpZW50cyI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMSIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIl0sIm5hbWUiOiJTYWdpdHRhbCBQbGFuZSBNZXRhY2FycG9waGFsYW5nZWFsIEZsZXhpb24gKElzb21ldHJpYykiLCJzb3VyY2VfbmFtZSI6IlNhZ2l0dGFsIFBsYW5lIE1ldGFjYXJwb3BoYWxhbmdlYWwgRmxleGlvbiAoSXNvbWV0cmljKSJ9LHsiY29lZmZpY2llbnRzIjpbIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIxIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwibmFtZSI6IlNhZ2l0dGFsIFBsYW5lIEludGVycGhhbGFuZ2VhbCBGbGV4aW9uIChJc29tZXRyaWMpIiwic291cmNlX25hbWUiOiJTYWdpdHRhbCBQbGFuZSBJbnRlcnBoYWxhbmdlYWwgRmxleGlvbiAoSXNvbWV0cmljKSJ9XX0=$matrix_payload$, 'base64'),
    'utf8'
  )::jsonb
);

do $$
declare
  matrix jsonb := (select payload from movement_muscle_matrix_import);
begin
  if jsonb_array_length(matrix -> 'patterns') <> 40
    or jsonb_array_length(matrix -> 'muscles') <> 40
  then
    raise exception 'Movement-to-muscle payload must be 40 by 40';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(matrix -> 'patterns') as pattern
    where jsonb_array_length(pattern -> 'coefficients') <> 40
  ) then
    raise exception 'Every movement-pattern row must contain 40 coefficients';
  end if;

  if (
    select count(*)
    from jsonb_array_elements(matrix -> 'patterns') with ordinality as source(pattern, source_order)
    join public.movement_patterns as catalogue
      on catalogue.source_order = source.source_order
     and catalogue.name = source.pattern ->> 'name'
  ) <> 40 then
    raise exception 'Movement-pattern rows do not exactly match the backend catalogue order';
  end if;

  if (
    select count(*)
    from jsonb_array_elements_text(matrix -> 'muscles') with ordinality as source(name, source_order)
    join public.muscles as catalogue
      on catalogue.source_order = source.source_order
     and catalogue.name = source.name
  ) <> 40 then
    raise exception 'Muscle columns do not exactly match the backend catalogue order';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(matrix -> 'patterns') as pattern
    cross join lateral jsonb_array_elements_text(pattern -> 'coefficients') as coefficient(value)
    where coefficient.value::numeric < 0 or coefficient.value::numeric > 1
  ) then
    raise exception 'Movement-to-muscle coefficients must be between 0 and 1';
  end if;
end
$$;

create table public.movement_muscle_mapping_versions (
  id bigint generated always as identity primary key,
  code text not null unique check (code ~ '^[a-z0-9_]+$'),
  name text not null check (btrim(name) <> ''),
  status text not null check (status in ('draft', 'published', 'retired')),
  is_current boolean not null default false,
  methodology_revision text not null check (btrim(methodology_revision) <> ''),
  source_file_name text not null check (btrim(source_file_name) <> ''),
  source_sha256 text not null check (source_sha256 ~ '^[0-9a-f]{64}$'),
  documentation_file_name text not null check (btrim(documentation_file_name) <> ''),
  documentation_sha256 text not null check (documentation_sha256 ~ '^[0-9a-f]{64}$'),
  payload_sha256 text not null check (payload_sha256 ~ '^[0-9a-f]{64}$'),
  movement_pattern_count integer not null check (movement_pattern_count > 0),
  muscle_count integer not null check (muscle_count > 0),
  cell_count integer not null check (cell_count = movement_pattern_count * muscle_count),
  nonzero_cell_count integer not null check (
    nonzero_cell_count >= 0 and nonzero_cell_count <= cell_count
  ),
  change_notes text not null check (btrim(change_notes) <> ''),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  check (not is_current or status = 'published'),
  check (
    (status = 'draft' and published_at is null)
    or (status in ('published', 'retired') and published_at is not null)
  )
);

create unique index movement_muscle_mapping_versions_one_current_idx
  on public.movement_muscle_mapping_versions (is_current)
  where is_current;

insert into public.movement_muscle_mapping_versions (
  code,
  name,
  status,
  is_current,
  methodology_revision,
  source_file_name,
  source_sha256,
  documentation_file_name,
  documentation_sha256,
  payload_sha256,
  movement_pattern_count,
  muscle_count,
  cell_count,
  nonzero_cell_count,
  change_notes,
  published_at
)
values (
  'initial_2026_08_10',
  'Initial 40 by 40 movement-pattern-to-muscle function matrix',
  'published',
  true,
  'Movement_Pattern_to_Muscle_Function_README.md@2026-08-10',
  'Movement_Pattern_to_Muscle_Function_Matrix.csv',
  'c0664168df7b971c84e24d5a9cebdf04ffde3c09c5eda8726a16559e539e50e2',
  'Movement_Pattern_to_Muscle_Function_README.md',
  '6710d2902397e385ebe779b93b7419b1b81e4f85a35770ea0784e2061f4cc3df',
  '595631fe61e70f75cc848c8caed75f047d16301ee3a42d541b5724a3121f6bf7',
  40,
  40,
  1600,
  112,
  'Initial functional-anatomy prior. Six source labels with em-dash qualifiers resolve explicitly to the existing parenthesized movement-pattern catalogue labels. Explicit zero-valued cells are retained.',
  now()
);

create table public.movement_pattern_muscle_coefficients (
  mapping_version_id bigint not null
    references public.movement_muscle_mapping_versions(id) on delete restrict,
  movement_pattern_id bigint not null
    references public.movement_patterns(id) on delete restrict,
  muscle_id bigint not null
    references public.muscles(id) on delete restrict,
  coefficient numeric(4, 3) not null check (coefficient between 0 and 1),
  rationale_status text not null default 'methodology_only'
    check (rationale_status in ('methodology_only', 'documented')),
  rationale text not null check (btrim(rationale) <> ''),
  created_at timestamptz not null default now(),
  primary key (mapping_version_id, movement_pattern_id, muscle_id)
);

create index movement_pattern_muscle_coefficients_muscle_idx
  on public.movement_pattern_muscle_coefficients (
    muscle_id,
    mapping_version_id,
    movement_pattern_id
  );

create index movement_pattern_muscle_coefficients_nonzero_idx
  on public.movement_pattern_muscle_coefficients (
    mapping_version_id,
    movement_pattern_id,
    muscle_id
  )
  where coefficient > 0;

insert into public.movement_pattern_muscle_coefficients (
  mapping_version_id,
  movement_pattern_id,
  muscle_id,
  coefficient,
  rationale_status,
  rationale
)
select
  version.id,
  movement_pattern.id,
  muscle.id,
  coefficient.value::numeric(4, 3),
  'methodology_only',
  case
    when coefficient.value::numeric = 0 then
      'The source functional-anatomy matrix does not map this muscle as a material producer of this movement pattern. No cell-specific rationale is documented.'
    else
      format(
        'The source functional-anatomy matrix assigns an independent coefficient of %s. The general evidence constraints are documented, but no cell-specific rationale is documented.',
        coefficient.value
      )
  end
from movement_muscle_matrix_import as source
cross join lateral jsonb_array_elements(source.payload -> 'patterns')
  with ordinality as pattern_source(pattern, pattern_order)
cross join lateral jsonb_array_elements_text(pattern_source.pattern -> 'coefficients')
  with ordinality as coefficient(value, muscle_order)
join public.movement_patterns as movement_pattern
  on movement_pattern.source_order = pattern_source.pattern_order
 and movement_pattern.name = pattern_source.pattern ->> 'name'
join public.muscles as muscle
  on muscle.source_order = coefficient.muscle_order
join public.movement_muscle_mapping_versions as version
  on version.code = 'initial_2026_08_10';

alter table public.movement_muscle_mapping_versions enable row level security;
alter table public.movement_pattern_muscle_coefficients enable row level security;

create policy "Authenticated users can read movement muscle mapping versions"
  on public.movement_muscle_mapping_versions
  for select to authenticated
  using (true);

create policy "Authenticated users can read movement muscle coefficients"
  on public.movement_pattern_muscle_coefficients
  for select to authenticated
  using (true);

revoke all on table public.movement_muscle_mapping_versions from anon, authenticated;
revoke all on table public.movement_pattern_muscle_coefficients from anon, authenticated;
grant select on table public.movement_muscle_mapping_versions to authenticated;
grant select on table public.movement_pattern_muscle_coefficients to authenticated;

comment on table public.movement_muscle_mapping_versions is
  'Immutable metadata for published movement-pattern-to-muscle functional-anatomy matrices.';
comment on table public.movement_pattern_muscle_coefficients is
  'Versioned functional coefficients connecting global movement patterns to canonical muscles. Values are independent priors, not percentages, force shares, or hypertrophy scores.';

do $$
declare
  version_id bigint := (
    select id
    from public.movement_muscle_mapping_versions
    where code = 'initial_2026_08_10'
  );
begin
  if (select count(*) from public.movement_pattern_muscle_coefficients where mapping_version_id = version_id) <> 1600
    or (select count(*) from public.movement_pattern_muscle_coefficients where mapping_version_id = version_id and coefficient > 0) <> 112
    or (select count(distinct movement_pattern_id) from public.movement_pattern_muscle_coefficients where mapping_version_id = version_id) <> 40
    or (select count(distinct muscle_id) from public.movement_pattern_muscle_coefficients where mapping_version_id = version_id) <> 40
  then
    raise exception 'Movement-pattern-to-muscle matrix validation failed';
  end if;
end
$$;

commit;
